version: '3'

services:
  telerelay:
    image: yanyuwangluo/telerelay:latest
    container_name: telerelay
    restart: unless-stopped
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - ./logs:/app/logs               # 日志文件映射
      - ./sessions:/app/sessions       # Telegram会话文件映射
    environment:
      - TZ=Asia/Shanghai               # 设置时区
      - TG_API_ID=${TG_API_ID:-}       # Telegram API ID
      - TG_API_HASH=${TG_API_HASH:-}   # Telegram API Hash
      - TG_PHONE=${TG_PHONE:-}         # 电话号码
    stdin_open: true  # 启用标准输入
    tty: true         # 分配伪终端