version: '3'

services:
  telerelay:
    build: .
    container_name: telerelay
    restart: unless-stopped
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - ./logs:/app/logs         # 日志文件映射
      - ./data:/app/data         # 数据目录映射
      - ./.env:/app/.env         # 配置文件映射
      - ./sessions:/app/sessions # Telegram会话文件映射
    environment:
      - TZ=Asia/Shanghai
      - TG_LOGIN_CODE=${TG_LOGIN_CODE:-}  # 如果需要传递验证码
      - TG_2FA_PASSWORD=${TG_2FA_PASSWORD:-}  # 如果需要传递二次验证密码
      - TG_ALWAYS_CONFIRM=${TG_ALWAYS_CONFIRM:-false}  # 是否自动确认
    command: python app.py 